### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by brachy84** [CleanroomMC/NeverEnoughAnimation#6]
- [ ] Move all (double click while holfing an item)
- [ ] Dragging maybe (scale in)
- [ ] throwing/pick up (scale in/out)
- [ ] Quark move buttons
- [ ] BogoSorter key combos
- [ ] MUI compat
